# Generated by Django 2.1.7 on 2019-03-02 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='书名')),
                ('author', models.CharField(max_length=64, verbose_name='作者')),
                ('type', models.CharField(max_length=64, verbose_name='类别')),
                ('up_time', models.CharField(max_length=64, verbose_name='上架时间')),
                ('borrow_time', models.CharField(max_length=64, verbose_name='借阅时间')),
                ('borrower', models.CharField(max_length=64, verbose_name='借阅人')),
                ('is_borrowed', models.BooleanField(verbose_name="是否已被借阅")),
            ],
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower', models.CharField(max_length=64, verbose_name='借阅人')),
                ('borrow_time', models.CharField(max_length=64, verbose_name='借阅时间')),
                ('return_time', models.CharField(max_length=64, verbose_name='归还时间')),
                ('is_return', models.BooleanField(verbose_name="是否已归还")),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsLib.BookInfo', verbose_name='借阅书籍')),
            ],
        ),
    ]
