# Generated by Django 2.1.7 on 2019-03-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsLib', '0002_auto_20190303_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='borrowed_time',
            field=models.TimeField(verbose_name='借阅时间'),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='up_time',
            field=models.TimeField(auto_now=True, verbose_name='上架时间'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='borrow_time',
            field=models.TimeField(auto_now=True, verbose_name='借阅时间'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='return_time',
            field=models.TimeField(verbose_name='归还时间'),
        ),
    ]
