# Generated by Django 2.1.7 on 2019-03-03 04:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tsLib', '0004_auto_20190303_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='borrowed_time',
            field=models.TimeField(default=datetime.datetime(2019, 3, 3, 4, 10, 18, 951127, tzinfo=utc), null=True, verbose_name='借阅时间'),
        ),
    ]
