# Generated by Django 2.1.7 on 2019-03-03 04:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tsLib', '0005_auto_20190303_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='borrowed_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 3, 4, 20, 4, 404406, tzinfo=utc), null=True, verbose_name='借阅时间'),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='up_time',
            field=models.DateTimeField(auto_now=True, verbose_name='上架时间'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='borrow_time',
            field=models.DateTimeField(auto_now=True, verbose_name='借阅时间'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='return_time',
            field=models.DateTimeField(null=True, verbose_name='归还时间'),
        ),
    ]
